server:
  port: 8081
  # ??????? ???????, ????? ??? ????????? ??????? SIGTERM ?? ????? ?? ????????
  # ????? ???????, ?? ??? ???? ???????? ??, ??? ??? ? ?????? ? ??????? ???????,
  # ??????? ??????? ? ????????? spring.lifecycle.timeout-per-shutdown-phase
  # ?? ????????? 30 ??????
  # ????????? ???: https://habr.com/en/companies/maxilect/articles/666090/
  shutdown: graceful
  tomcat:
    # ??????? Tomcat ??????? ??????? ????? ????? ???????? ?????????? ?? ????????? ???????.
    # ????? ???? ??????? ??? ?????? ?? DoS ????, ????? ?????? ????????????? ??????????,
    # ?????? ???????? ????? ??? ??? ?????????, ?? ?????? ?? ????????.
    # ??? ?? ????? Tomcat ????? ??????? ?? ?????? ???? ???????.
    connection-timeout: 3s
    # ?????, ? ??????? ???????? Tomcat ?????????? ?????????? ????????, ?????? ????? ????????
    keep-alive-timeout: 20s
    # Tomcat ?????????? ??? ??????? ??? ????????? ???????? ??????????: ???? ?????????? - ???? ?????.
    # ?? ????????? ??????????? ?????????? ??????? ? ???? - 200.
    threads:
      max: 200
      # ??????????? ?????????? ???????, ??????? ????? ??????? ? ???? ??? ?????? ???????
      min-spare: 10
spring:
  application:
    name: product-service
  lifecycle:
    timeout-per-shutdown-phase: 30s # ?????, ? ??????? ???????? ??????? ??????? ????? ?????????????? ????? ????????? ??????? SIGTERM
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/product_service_db
    hikari:
      # ??????? ?? ????????? ?????????? ?? ???? ??????????
      connection-timeout: 2000 # ? ?????????????
      # ?? ????????? ? ?????????? ???????????? ??? ?????????? ? ?? HikariCP.
      # ??? ?????? ??????????????? ???? ??????????. ??????????? ??????? HikariCP ???????????
      # ????????????? ?????????? ??????????, ?????? ?? ???????:
      # connections = ((core_count * 2) + effective_spindle_count)
      # ??? core_count - ?????????? ???? ??????????
      # effective_spindle_count - ?????????? ??????????? ??????
      # ??? ??? ?? ????????????, ??? ????? ?????????????? SSD, ??????????? ?????? ?? ?????,
      # ??????? effective_spindle_count = 0
      # ?? ????? ????????????, ??? ?????????? ???? = 6, ????????????? maximum-pool-size = 12
      # ????? ???????? ???: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      maximum-pool-size: 12
  jpa:
    hibernate:
      # ??????? hibernate, ??? ?????????? ??????????????? ???????????? ????? ?? ? JPA ??????
      ddl-auto: validate
    properties:
      hibernate:
        # ??????? hibernate, ????? ????????? ? ???? sql ??????? ???? ?????????????? ??? ???????? ??????
        format_sql: true
        # ??????? hibernate ?????????? sql ??????? ? ????? (??? ??????? ? ????????????)
        show_sql: true
    open-in-view: false
  # https://stackoverflow.com/a/69739888
  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check:
        enabled: false
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      label: master

configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9095}

