version: "3.8"
services:
  config-server:
    image: "config-server"
    container_name: "config-server"
    environment:
      - THC_PATH=/actuator/health
      - THC_PORT=8085
    ports:
      - "8085:8085"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  product-service:
    image: "product-service"
    container_name: "product-service"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - CONFIGSERVER_IMPORT=configserver:${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DB_URL=${PRODUCT_DB_URL}

  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "product_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db-data:
    driver: local